FROM nginx

#copying over the local default.conf contents into nginx.conf file of nginx container.
 #Also overrite existing file with the same name (as in this case).
COPY ./default.conf /etc/nginx/conf.d/default.conf
